### ISSUE TITLE
Generation of -package option for module being developed

### ISSUE THREAD

**Issue by 2chilled** [dan-t/cabal-cargs#4]
Running `cabal-cargs --format=ghc -r` on a cabal project with a test-suite depending on the library being tested outputs `-package=<LIBRARY>` where `<LIBRARY>` is the library being tested. So for example if you develop a library called "my-library" with a test-suite depending on the library `<LIBRARY>` is substituted by "my-library". This is bad, as it requires the library being installed already by `cabal install my-library` or else one gets an error `<command line>: cannot satisfy -package my-library`

So it would be quite nice if cabal-cargs would suppress the library under test from its `-package` output. What do you think?

**Comment by dan-t** [comment]
What is your concrete use case? Are you sure that you want to use the `--relative` option?

There are cases were you want to have the library package. If you're building in a
`cabal sandbox` and want to build your test suite, then you will need the
library package and it also will be installed in the package database of the sandbox,
so just leaving it out isn't an option.
